settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: NAES # unique identifier
    name: naranjasamparo.net
    description: 'NAES' # default=empty
    url: 'https://naranjasamparo.net/es' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: NADE # unique identifier
    name: orangenfrischnachhause.de
    description: 'NADE' # default=empty
    url: 'https://orangenfrischnachhause.de/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: NAFR # unique identifier
    name: naranjasamparo.fr
    description: 'NA-FR' # default=empty
    url: 'https://naranjasamparo.fr/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
  
  - id: CRC-LASAFOR
    name: crclasafor.com
    description: 'Centro Reconocimiento Medico La Safor.'
    url: 'https://www.crclasafor.com'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: blog-NAES
    name: NAES BLOG
    url: 'https://naranjasamparo.net/blog'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: blog-NADE
    name: NADE BLOG
    url: 'https://orangenfrischnachhause.de/blog'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: BOATIK # unique identifier
    name: boatik.es
    description: 'BOATIK' # default=empty
    url: 'https://boatik.es' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: SailingTripsMallorca # unique identifier
    name: sailingtripsmallorca.com
    description: 'Sailing Trips Mallorca.' # default=empty
    url: 'https://www.sailingtripsmallorca.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
