settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: NAES # unique identifier
    name: NAES - Prod
    description: 'NAES' # default=empty
    url: 'https://naranjasamparo.net/es/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: NADE # unique identifier
    name: NADE - Prod
    description: 'NADE' # default=empty
    url: 'https://orangenfrischnachhause.de' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: NAFR # unique identifier
    name: NAFR - Prod
    description: 'NA-FR' # default=empty
    url: 'https://naranjasamparo.fr/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
  
  - id: blog-NAES
    name: NAES blog
    url: 'https://naranjasamparo.net/blog/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: blog-NADE
    name: NADE blog
    url: 'https://orangenfrischnachhause.de/blog/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: blog-NAFR
    name: NAFR blog
    url: 'https://naranjasamparo.fr/blog/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: BOATIK # unique identifier
    name: Boatik.es - Prod
    description: 'BOATIK' # default=empty
    url: 'https://boatik.es' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: STM # unique identifier
    name: SailingTripsMallorca.com - Prod
    description: 'Sailing Trips Mallorca.' # default=empty
    url: 'https://www.sailingtripsmallorca.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: NAUTIC # unique identifier
    name: nauticadventure.com - Prod
    description: 'Nautic Adventure' # default=empty
    url: 'https://www.nauticadventure.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: crclasafor
    name: crclasafor
    description: 'Centro Reconocimiento Medico La Safor.'
    url: 'https://www.crclasafor.com'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
